# Generated by Django 4.0.6 on 2024-05-15 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PropertiesExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FOR SALE', 'For Sale'), ('OFF PLAN', 'Off Plan')], default='FOR SALE', max_length=20)),
                ('category', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('RENTAL', 'Rental'), ('SALE', 'Sale')], default='SALE', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.CharField(max_length=20)),
                ('bathrooms', models.CharField(max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location', models.CharField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='media/property_images/')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='media/property_brochures/')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FOR SALE', 'For Sale'), ('OFF PLAN', 'Off Plan')], default='FOR SALE', max_length=20)),
                ('property_type', models.CharField(choices=[('RENTAL', 'Rental'), ('SALE', 'Sale')], default='SALE', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=20)),
                ('bedrooms', models.CharField(max_length=20)),
                ('bathrooms', models.CharField(max_length=20)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brochure', models.FileField(blank=True, null=True, upload_to='media/property_brochures/')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/property_images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Real_Estate_App.property')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Real_Estate_App.propertycategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Real_Estate_App.developer'),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Real_Estate_App.location'),
        ),
    ]
