# Generated by Django 4.0.6 on 2024-05-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Real_Estate_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
