# Generated by Django 4.0.6 on 2024-05-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Real_Estate_App', '0002_remove_location_latitude_remove_location_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
